apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculadora-service
  template:
    metadata:
      labels:
        app: calculadora-service
    spec:
      containers:
        - name: calculadora-service
          image: jorgehrique/sok-calculadora-service:1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 350m
              memory: 120Mi
            limits:
              cpu: 700m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5