apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculadora-service
  labels:
    app: calculadora
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculadora-service
  template:
    metadata:
      labels:
        app: calculadora-service
    spec:
      containers:
        - name: calculadora-service
          image: jorgehrique/calculadora-service:0.0.1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3